version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  celery-worker:
    build:
      context: ./celery_worker
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
